### ISSUE TITLE
Указание адреса счётчика

### ISSUE THREAD

**Issue by bushmaks** [Brokly/ESPHome-Mercury230#3]
Привет, хотелось бы иметь возможность указать адрес счётчика, так как у меня в доме эти счётчики в одной сети, спасибо!

**Comment by Brokly** [comment]
Если у вас счетчики в одной сети, то они имеют ведущий узел. Вероятно это контролер который принадлежит управляющей компании. В модбас сети не может быть два ведущих узла. Данный код написан для создания ведущего устройства. Именно поэтому я сделал авто определение адреса. То есть , этот компонент может работать только в сети с одним счетчиком. Есть способ прослушать обмен вашего счетчика с узлом управляющей компании, но скорее всего , компания снимает только текущие показания. К тому же этот способ требует большой переделки кода, которую я не планирую. Можете использовать мой код как основу для переработки. Извините, но больше  ничем помочь не смогу.

**Comment by Brokly** [comment]
Подумал и решил.. А дам возможность установки паролей и адреса. Берите на себя ответственность и сами разбирайтесь со своими управляющими компаниями :)

**Comment by Brokly** [comment]
Сделал возможность задать адрес и пароль, см. пример конфигурации
