### ISSUE TITLE
Показания по тарифам

### ISSUE THREAD

**Issue by sergeibush** [Brokly/ESPHome-Mercury230#6]

**Comment by sergeibush** [comment]
Здравствуйте, можно добавить снятие показаний по тарифам?

**Comment by Brokly** [comment]
К сожалению, мой счетчик не поддерживает этот режим. Отлаживать негде.

**Comment by DieMetRik** [comment]
Добрый вечер.

Добавил просмотр по тарифам. Вот репа. [Github](https://github.com/DieMetRik/mercury_esphome/tree/main/mercury-230)
Если автор не против.

У меня счетчика такого нет, но удалось протестировать код у человека со счетчиком.
