### ISSUE TITLE
возможность подключения напрямую через RS-485

### ISSUE THREAD

**Issue by Anzic23** [Brokly/ESPHome-Mercury230#8]
скажите, а можно ли доработать ваш компонент, что бы можно было подключиться через TCP? 
У меня несколько лет работало на такой связке Меркурий 230 ART-01 CN -> MOXA 485 to TCP -> iobroker . У последнего есть адаптер, который подключается и собирает все данные с счетчика, но с крайним обновлением, адаптер отказался работать. Давно хочу перевести этот счетчик на ХА, но все никак не попадается готовая, рабочая интеграция :(

**Comment by Brokly** [comment]
Я не понял вопроса. Этот компонент и так подключается к счетчику по 485 интерфейсу, а передает данные серверу по TCP.

**Comment by Brokly** [comment]
Поскольку нет реакции и пояснений считаю запрос не актуальным.

**Comment by Anzic23** [comment]
Прошу прощения, "проморгал" ваш ответ. Не совсем понимаю, как тогда нужно его настроить, если из "выходных" данных у меня есть ip адрес и порт, через который адаптер iobroker забирает все данные с счетчика. У вас в примере идет esp. Может можете подсказать, как будет выглядеть конфиг в моем случае?
